### ISSUE TITLE
Convert pulp-selinux docs to new stack

### ISSUE THREAD

**Issue by pedro-psb** [pulp/pulpcore-selinux#73]
The general workflow for this task can be found [here](https://hackmd.io/@pbrochad/SyfGeQc86#Content-Migration).

**Comment by ekohl** [comment]
> The general workflow for this task can be found [here](https://hackmd.io/@pbrochad/SyfGeQc86#Content-Migration).

That document shows a permission denied.

**Comment by pedro-psb** [comment]
My bad, I've changed read permissions.

**Comment by ekohl** [comment]
Still uses private data:
> The motivation behind having tmp_dir is explained in this [presentation](https://miro.com/app/board/uXjVN8JT3bU=/?moveToWidget=3458764574957791463&cot=14) (3 min).
Also requires a login.

It's still not clear to me what this issue is about. Do you want to move things from README to some other place?

**Comment by pedro-psb** [comment]
I just realized I can't share the Miro board outside redhat, but that wont be necessary here, anyway.

This case is specially simple, but if you are interested you are welcome to show up in the Docs Office Hours to learn more.
You can found more about it [here](https://discourse.pulpproject.org/t/unified-docs-plan/1059/5?u=pedro-psb).

**Comment by ekohl** [comment]
> I just realized I can't share the Miro board outside redhat, but that wont be necessary here, anyway.

I could probably use my Red Hat login, but I hold my colleagues to a higher standard. Open source development means using public resources.

**Comment by pedro-psb** [comment]
Sure, I'll look for an alternative for sharing it, it was not my intention to keep it private.
Thanks for pointing it out.
